# Generated by Django 4.2.8 on 2023-12-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='order_part',
            field=models.CharField(choices=[('front glass', 'front glass'), ('Back glass', 'Back glass'), ('Pair of front windows', 'Pair of front windows'), ('Pair of rear windows', 'Pair of rear windows'), ('Front lighting', 'Front lighting'), ('Backlight', 'Backlight')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
