# Generated by Django 4.2.8 on 2023-12-25 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_title', models.CharField(max_length=250)),
                ('order_customers_name', models.CharField(max_length=250, null=True, unique=True)),
                ('mobile_phone', models.IntegerField(null=True)),
                ('car_plate_number', models.IntegerField(null=True)),
                ('car_type', models.CharField(max_length=250, null=True)),
                ('car_color', models.CharField(max_length=250, null=True)),
                ('car_models', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_notes', models.CharField(max_length=1200)),
                ('order_part', models.CharField(choices=[('front glass', 'front glass'), ('Back glass', 'Back glass'), ('Pair of front windows', 'Pair of front windows'), ('Pair of rear windows', 'Pair of rear windows'), ('Front lighting', 'Front lighting'), ('Backlight', 'Backlight')], max_length=250)),
            ],
        ),
    ]
