# Generated by Django 5.0 on 2023-12-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_customers_name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
